<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_menu().
 */
function import_folders_menu() {
  return array(
    'admin/config/system/cmis-import-folders' => array(
      'title' => t('Set Root location for CMIS importing of folders'), 
      'page callback' => 'drupal_get_form',
      'page arguments' => array('import_folders_admin_settings'),
      'access callback' => 'user_access',
      'access arguments' => array('administer cmis'),
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}
/**
 * Admin form for configuring root folder to import.
 * @return array
 *   Form to render.
 */
function import_folders_admin_settings() {
  $form = array();
  $form['import_folders_cmis_root'] = array(
    '#title' => t('Root Directory'),
    '#description' => t('Root folder for CMIS importing folders from.'),
    '#type' => 'textfield',
    '#default_value' => variable_get(
      'import_folders_cmis_root',
      'workspace://SpacesStore/8f2105b4-daaf-4874-9e8a-2152569d109b'
    ),
  );
  return system_settings_form($form);
}
/**
 * Implements hook_theme().
 */
function import_folders_theme($existing, $type, $theme, $path) {
  return array();
}
/**
 * Implements hook_cron().
 */
function import_folders_cron() {
  // Default is /Sites/swsdp/documentLibrary for demo Alfresco data.
  $root = variable_get(
    'import_folders_cmis_root',
    'workspace://SpacesStore/8f2105b4-daaf-4874-9e8a-2152569d109b'
  );
  $vocab = taxonomy_vocabulary_machine_name_load('cmis_folders');
  _import_folders_find($root, $vocab->vid, 0);
}

function _import_folders_find($root, $vid, $parent_tid) {
  $query = sprintf(
    "SELECT * FROM cmis:folder F WHERE IN_FOLDER(F, '%s')",
    $root
  );
  $result = _import_folders_query($query);
  if ($result === FALSE) {
    return 0;
  }
  $children = taxonomy_get_children($parent_tid, $vid);
  $child_ids = array_keys($children);
  foreach ($result->objectList as $folder) {
    $list = taxonomy_get_term_by_name(
      $folder->properties['cmis:name'],
      'cmis_folders'
    );
    $term = FALSE;
    if (count($list) > 0) {
      $list_ids = array_keys($list);
      foreach ($list_ids as $id) {
        if ($parent_tid == 0) {
          $term = array_shift($list);
        }
        elseif (in_array($id, $child_ids)) {
          $term = $list[$id];
        }
      }      
    }
    if ($term === FALSE) {
      $term = new \stdClass();
      $term->vid = $vid;
      $term->name = $folder->properties['cmis:name'];
      $term->parent = $parent_tid;
      taxonomy_term_save($term);
    }
    _import_folders_find($folder->properties['cmis:objectId'], $vid, $term->tid);
    _import_folders_find_docs($folder->properties['cmis:objectId'], $term->tid);
  }
}
function _import_folders_find_docs($root, $tid) {
  $cmis_query = sprintf(
    "SELECT * FROM cmis:document D WHERE IN_FOLDER(D, '%s')",
    $root
  );
  $cmis_result = _import_folders_query($cmis_query);
  $cmis_ids = array_keys($cmis_result->objectsById);
  if (!empty($cmis_ids)) {
    $query = db_select('cmis_sync_node', 'CSN');
    $query->fields('CSN', array('nid'))
      ->condition('cmis_objectId', $cmis_ids, 'IN');
    $result = $query->execute();
    foreach ($result as $row) {
      $node = node_load($row->nid);
      $node->field_folder[LANGUAGE_NONE][0]['tid'] = $tid;
      node_save($node);
    }
  }
}
function _import_folders_query($query) {
  module_load_include('api.inc', 'cmis');
  $query_result = FALSE;
  try {
    $repository = cmisapi_getRepositoryInfo();
    $repoId = !empty($repository->repositoryId) ? $repository->repositoryId : 'default';
    $query_result = cmisapi_query($repoId, $query);
  }
  catch (CMISException $e) {
    cmis_error_handler('cmis_query', $e);
  }
  return $query_result;
}
